### ISSUE TITLE
appendChunk Fails for GraphQL mutations with multipart/form-data content-type

### ISSUE THREAD

**Issue by zevstravitz** [Moesif/moesif-nodejs#64]
Getting error:
```
TypeError: The "list[0]" argument must be an instance of Buffer or Uint8Array. Received type string ('{ "msg": "request body s...)
    at new NodeError (node:internal/errors:372:5)
    at Function.concat (node:buffer:560:13)
    at appendChunk (/Users/username/Rutter/rutter-backend/node_modules/moesif-nodejs/lib/dataUtils.js:301:27)
    at IncomingMessage.passedOnFunction (/Users/username/Rutter/rutter-backend/node_modules/moesif-nodejs/lib/index.js:272:44)
    at IncomingMessage.emit (node:events:527:28)
    at IncomingMessage.emit (node:domain:475:12)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at IncomingMessage.Readable.push (node:internal/streams/readable:234:10)
    at HTTPParser.parserOnBody (node:_http_common:141:24)
```
## Context
Error surfaces when Moesif is added to express middleware and we send GraphQL mutations to backend involving Apollo `Upload` type (request with multipart/form-data content-type)

Is there a way around this error, or is there an underlying bug in [`appendChunk` ](https://github.com/Moesif/moesif-nodejs/blob/5c17ce026015d466817b45c0a985a2d6d05b7ca3/lib/dataUtils.js#L297) that makes assumptions about the Buffer type?

**Comment by xinghengwang** [comment]
Thanks for raising the issue. 
Does seems to be a more nodejs issue with appendChunk.
I will let someone investigate to see if there is a work around.

**Comment by xinghengwang** [comment]
@zevstravitz  So since it is a file upload task. Generally, API analytics don't try to capture file uploads, it would be too big.

For now, a simple workaround is the "skip" function if it is a file upload. 

https://github.com/Moesif/moesif-nodejs#skip

Would this work for now?

**Comment by zevstravitz** [comment]
Hi @xinghengwang, thanks for the help and prompt response! Using the skip function by checking the request content-type works for our use case, so for now our issue is solved 😄
